# Generated by Django 5.2.7 on 2025-11-13 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Road', 'Road'), ('Water', 'Water'), ('Electricity', 'Electricity'), ('Garbage', 'Garbage'), ('Sewage', 'Sewage'), ('Street Light', 'Street Light'), ('Public Park', 'Public Park'), ('Drainage', 'Drainage'), ('Traffic', 'Traffic'), ('Others', 'Others')], max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('priority', models.CharField(choices=[('One Day', 'Within a day'), ('One Week', 'Within a week'), ('One Month', 'Within a month')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('contact_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Delayed', 'Delayed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='citygram.complaint')),
            ],
        ),
    ]
